apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: authors
  namespace: istio-course
spec:
  host: authors
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service-author-delay
  namespace: istio-course
spec:
  hosts:
  - authors
  http:
  - fault:
      delay:
        fixedDelay: 65s
        percentage:
          value: 100
    route:
    - destination:
        host: authors
        subset: v1