apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service-author-fault
  namespace: istio-course
spec:
  hosts:
  - authors
  http:
  - fault:
      abort:
        httpStatus: 500
        percentage:
          value: 100
    route:
    - destination:
        host: authors
        subset: v1